micronaut:
  application:
    name: keyManagerREST

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10